// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package domain

import (
	"tirenn/test-efishery/fetch-app/domain/fetch"
)

// Injectors from wire.go:

func InitFetchAPI(baseUrl string) fetch.ControllerContract {
	repositoryContract := fetch.NewRepository(baseUrl)
	serviceContract := fetch.NewService(repositoryContract)
	controllerContract := fetch.NewController(serviceContract)
	return controllerContract
}
